#using postgresql

import os
import psycopg
from psycopg_pool import ConnectionPool
from dotenv import load_dotenv
from datetime import datetime, timedelta
import json
import time
load_dotenv()


DATABASE_URL = os.getenv("DATABASE_URL")
print(DATABASE_URL)

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL не задан")


pool = ConnectionPool(
    conninfo=DATABASE_URL,
    min_size=2,
    max_size=10,
    open=True
)


#def get_connection():
#    return pool.connection()



def create_tables():
    with pool.connection() as conn:
        try:
            with conn.cursor() as cursor:

                # ============================================================
                # USERS
                # ============================================================

                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS users (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL UNIQUE,
                        user_name TEXT,
                        email TEXT
                    );
                """)

                # ============================================================
                # LEVELS
                # ============================================================

                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS levels (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        code TEXT NOT NULL UNIQUE,
                        sort_order INTEGER NOT NULL
                    );
                """)

                # ============================================================
                # SUBSCRIPTIONS
                # ============================================================

                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS subscriptions (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        code TEXT NOT NULL UNIQUE,
                        name TEXT NOT NULL,
                        price INTEGER NOT NULL DEFAULT 0,
                        period_months INTEGER,
                        daily_limit INTEGER
                    );
                """)

                # ============================================================
                # DIFFICULTY
                # ============================================================

                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS difficulty (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name TEXT NOT NULL,
                        description TEXT,
                        description_short TEXT
                    );
                """)

                # ============================================================
                # GRAMMAR TOPICS
                # ============================================================

                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS grammar_topics (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name TEXT NOT NULL,
                        parent_id BIGINT,
                        level_id BIGINT,

                        FOREIGN KEY (parent_id)
                            REFERENCES grammar_topics(id),

                        FOREIGN KEY (level_id)
                            REFERENCES levels(id)
                    );
                """)

                # ============================================================
                # LEXICAL TOPICS
                # ============================================================

                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS lexical_topics (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name TEXT NOT NULL,
                        parent_id BIGINT,
                        level_from BIGINT NOT NULL,
                        subscription_id BIGINT NOT NULL DEFAULT 1,

                        FOREIGN KEY (parent_id)
                            REFERENCES lexical_topics(id),

                        FOREIGN KEY (level_from)
                            REFERENCES levels(id),

                        FOREIGN KEY (subscription_id)
                            REFERENCES subscriptions(id)
                    );
                """)

                # ============================================================
                # SENTENCES
                # ============================================================

                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS sentences (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        sentence TEXT NOT NULL,
                        level_id BIGINT NOT NULL,
                        grammar_topic_id BIGINT,
                        lexical_topic_id BIGINT,
                        difficulty_id BIGINT,
                        type INTEGER NOT NULL DEFAULT 0,
                        tips TEXT,
                        translation TEXT,

                        FOREIGN KEY (level_id)
                            REFERENCES levels(id),

                        FOREIGN KEY (grammar_topic_id)
                            REFERENCES grammar_topics(id),

                        FOREIGN KEY (lexical_topic_id)
                            REFERENCES lexical_topics(id),

                        FOREIGN KEY (difficulty_id)
                            REFERENCES difficulty(id)
                    );
                """)

                # ============================================================
                # PAYMENTS
                # ============================================================

                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS payments (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        subscription_id BIGINT NOT NULL,
                        yookassa_payment_id TEXT NOT NULL UNIQUE,
                        amount INTEGER NOT NULL,
                        currency TEXT NOT NULL DEFAULT 'RUB',
                        status TEXT NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        paid_at TIMESTAMP,

                        FOREIGN KEY (user_id)
                            REFERENCES users(user_id),

                        FOREIGN KEY (subscription_id)
                            REFERENCES subscriptions(id)
                    );
                """)

                # ============================================================
                # USER ANSWERS
                # ============================================================

                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS user_answers (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        sentence_id BIGINT NOT NULL,
                        user_answer TEXT,
                        ai_answer TEXT,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                        FOREIGN KEY (user_id)
                            REFERENCES users(user_id),

                        FOREIGN KEY (sentence_id)
                            REFERENCES sentences(id)
                    );
                """)

                # ============================================================
                # USER DIFFICULTY
                # ============================================================

                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS user_difficulty (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        difficulty_id BIGINT NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                        FOREIGN KEY (user_id)
                            REFERENCES users(user_id),

                        FOREIGN KEY (difficulty_id)
                            REFERENCES difficulty(id)
                    );
                """)

                # ============================================================
                # USER LEVELS
                # ============================================================

                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS user_levels (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        user_level TEXT,
                        estimated_level TEXT,
                        source TEXT NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                        FOREIGN KEY (user_id)
                            REFERENCES users(user_id)
                    );
                """)

                # ============================================================
                # USER SUBSCRIPTIONS
                # ============================================================

                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS user_subscriptions (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                        user_id BIGINT NOT NULL,
                        subscription_id BIGINT NOT NULL,
                        payment_id BIGINT NOT NULL,

                        started_at TIMESTAMP NOT NULL,
                        expires_at TIMESTAMP NOT NULL,

                        FOREIGN KEY (user_id)
                            REFERENCES users(user_id),

                        FOREIGN KEY (subscription_id)
                            REFERENCES subscriptions(id),

                        FOREIGN KEY (payment_id)
                            REFERENCES payments(id),

                        UNIQUE(payment_id)
                    );
                """)

            conn.commit()

        except Exception:
            conn.rollback()
            raise

        finally:
            conn.close()


def add_user(telegram_id: int, username: str):
    with pool.connection() as conn:
        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT id
                    FROM users
                    WHERE user_id = %s
                """, (telegram_id,))

                user = cursor.fetchone()

                if user is not None:
                    return False

                cursor.execute("""
                    INSERT INTO users (
                        user_id,
                        user_name
                    )
                    VALUES (%s, %s)
                """, (
                    telegram_id,
                    username
                ))

            conn.commit()
            return True

        except Exception:
            conn.rollback()
            raise

     


# ============================================================
# LEVELS
# ============================================================

def seed_levels():
    levels = [
        ("A1", 1),
        ("A2", 2),
        ("B1", 3),
        ("B2", 4),
        ("C1", 5),
        ("C2", 6),
    ]

    with pool.connection() as conn:
        try:
            with conn.cursor() as cursor:

                cursor.executemany("""
                    INSERT INTO levels (code, sort_order)
                    VALUES (%s, %s)
                    ON CONFLICT (code) DO NOTHING
                """, levels)

            conn.commit()

        except Exception:
            conn.rollback()
            raise

       
    print("Уровни добавлены.")


# ============================================================
# GRAMMAR TOPICS
# ============================================================

def seed_grammar_topics():
    with pool.connection() as conn:
        try:
            with conn.cursor() as cursor:

                groups = [
                    "Времена",
                    "Условные предложения",
                    "Модальные глаголы",
                    "Артикли",
                    "Местоимения",
                    "Предлоги",
                    "Степени сравнения",
                    "Пассивный залог",
                    "Инфинитив и герундий",
                    "Порядок слов",
                ]

                group_ids = {}

                # ----------------------------------------------------
                # GROUPS
                # ----------------------------------------------------

                for group_name in groups:

                    cursor.execute("""
                        SELECT id
                        FROM grammar_topics
                        WHERE name = %s
                        AND parent_id IS NULL
                    """, (group_name,))

                    row = cursor.fetchone()

                    if row:
                        group_id = row[0]

                    else:
                        cursor.execute("""
                            INSERT INTO grammar_topics (
                                name,
                                parent_id
                            )
                            VALUES (%s, NULL)
                            RETURNING id
                        """, (group_name,))

                        group_id = cursor.fetchone()[0]

                    group_ids[group_name] = group_id

                # ----------------------------------------------------
                # SUBTOPICS
                # ----------------------------------------------------

                topics = {
                    "Времена": [
                        "Present Simple",
                        "Present Continuous",
                        "Past Simple",
                        "Past Continuous",
                        "Future Simple",
                        "Present Perfect",
                        "Present Perfect Continuous",
                        "Past Perfect",
                        "Past Perfect Continuous",
                        "Future Continuous",
                        "Future Perfect",
                    ],

                    "Условные предложения": [
                        "Zero Conditional",
                        "First Conditional",
                        "Second Conditional",
                        "Third Conditional",
                    ],

                    "Модальные глаголы": [
                        "Can / Could",
                        "Must / Have to",
                        "Should",
                        "May / Might",
                        "Need",
                    ],

                    "Артикли": [
                        "A / An",
                        "The",
                        "Zero Article",
                    ],

                    "Местоимения": [
                        "Personal Pronouns",
                        "Possessive Pronouns",
                        "Object Pronouns",
                        "Reflexive Pronouns",
                        "Demonstrative Pronouns",
                    ],

                    "Предлоги": [
                        "Prepositions of Time",
                        "Prepositions of Place",
                        "Prepositions of Movement",
                    ],

                    "Степени сравнения": [
                        "Comparative",
                        "Superlative",
                    ],

                    "Пассивный залог": [
                        "Present Simple Passive",
                        "Past Simple Passive",
                        "Future Simple Passive",
                        "Present Perfect Passive",
                    ],

                    "Инфинитив и герундий": [
                        "Infinitive",
                        "Gerund",
                        "Verb + Infinitive",
                        "Verb + Gerund",
                    ],

                    "Порядок слов": [
                        "Basic Word Order",
                        "Questions",
                        "Negative Sentences",
                        "Adverbs Position",
                    ],
                }

                for group_name, topic_names in topics.items():

                    parent_id = group_ids[group_name]

                    for topic_name in topic_names:

                        cursor.execute("""
                            SELECT id
                            FROM grammar_topics
                            WHERE name = %s
                            AND parent_id = %s
                        """, (
                            topic_name,
                            parent_id
                        ))

                        exists = cursor.fetchone()

                        if not exists:
                            cursor.execute("""
                                INSERT INTO grammar_topics (
                                    name,
                                    parent_id
                                )
                                VALUES (%s, %s)
                            """, (
                                topic_name,
                                parent_id
                            ))

            conn.commit()

        except Exception:
            conn.rollback()
            raise

    

    print("Грамматические темы добавлены.")


# ============================================================
# GRAMMAR TOPICS
# ============================================================

def get_grammar_topics_old(parent_id: int | None, level_id: int):

    with pool.connection() as conn:
        try:
            with conn.cursor() as cursor:

                if parent_id is None:

                    cursor.execute("""
                        SELECT id, name
                        FROM grammar_topics
                        WHERE parent_id IS NULL
                        AND level_id = %s
                    """, (level_id,))

                else:

                    cursor.execute("""
                        SELECT id, name
                        FROM grammar_topics
                        WHERE parent_id = %s
                        AND level_id = %s
                    """, (
                        parent_id,
                        level_id
                    ))

                return cursor.fetchall()

        except Exception:
            conn.rollback()
            raise




def get_grammar_topics(parent_id: int | None, level_id: int):

    with pool.connection() as conn:
        try:
            with conn.cursor() as cursor:

                if parent_id is None:

                    cursor.execute("""
                        SELECT id, name
                        FROM grammar_topics
                        WHERE parent_id IS NULL
                    """)

                else:

                    cursor.execute("""
                        SELECT id, name
                        FROM grammar_topics
                        WHERE parent_id = %s
                    """, (parent_id,))

                return cursor.fetchall()

        except Exception:
                    conn.rollback()
                    raise


# ============================================================
# LEXICAL TOPICS
# ============================================================

def get_lexical_topics(parent_id: int | None, level_id: int):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                if parent_id is None or parent_id == 0:

                    cursor.execute("""
                        SELECT id, name
                        FROM lexical_topics
                        WHERE parent_id IS NULL
                        AND level_from <= %s
                    """, (level_id,))

                else:

                    cursor.execute("""
                        SELECT id, name
                        FROM lexical_topics
                        WHERE parent_id = %s
                        AND level_from <= %s
                    """, (
                        parent_id,
                        level_id
                    ))

                return cursor.fetchall()

        except Exception:
                    conn.rollback()
                    raise
        


# ============================================================
# TOPIC RELATIONS
# ============================================================

def get_parent_grammar_topic_id(topic_id: int):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT parent_id
                    FROM grammar_topics
                    WHERE id = %s
                """, (topic_id,))

                result = cursor.fetchone()

                if result is None:
                    return None

                return result[0]
        except Exception:
                    conn.rollback()
                    raise
        


def get_grammar_topic_level_id(grammar_topic_id: int) -> int | None:

    with pool.connection() as conn:
        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT level_id
                    FROM grammar_topics
                    WHERE id = %s
                """, (grammar_topic_id,))

                result = cursor.fetchone()

                if result is None:
                    return None

                return result[0]

        except Exception:
            conn.rollback()
            raise



def get_random_grammar_topic_2(parent_id: int, level_id: int) -> int | None:

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT id
                    FROM grammar_topics
                    WHERE parent_id = %s
                    AND (
                        level_id = %s
                        OR level_id IS NULL
                    )
                    ORDER BY RANDOM()
                    LIMIT 1
                """, (
                    parent_id,
                    level_id
                ))

                result = cursor.fetchone()

                if result is None:
                    return None

                return result[0]

        except Exception:
            conn.rollback()
            raise
    


def get_parent_lexical_topic_id(topic_id: int):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT parent_id
                    FROM lexical_topics
                    WHERE id = %s
                """, (topic_id,))

                result = cursor.fetchone()

                if result is None:
                    return None

                return result[0]

        except Exception:
            conn.rollback()
            raise
            



def get_topics_count(parent_id, level_id: int) -> int:

    with pool.connection() as conn:
        with conn.cursor() as cursor:

            cursor.execute("""
                SELECT COUNT(id)
                FROM grammar_topics
                WHERE parent_id = %s
                  AND level_id = %s
            """, (
                parent_id,
                level_id
            ))

            return cursor.fetchone()[0]

  


# ============================================================
# SENTENCES
# ============================================================

def save_sentence(
    sentence: str,
    translation: str,
    tips: str,
    level_id: int,
    grammar_topic_id: int | None,
    lexical_topic_id: int | None,
    difficulty_id: int,
    sentence_type: int = 0
):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    INSERT INTO sentences (
                        sentence,
                        translation,
                        tips,
                        level_id,
                        grammar_topic_id,
                        lexical_topic_id,
                        difficulty_id,
                        type
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                    RETURNING id
                """, (
                    sentence,
                    translation,
                    tips,
                    level_id,
                    grammar_topic_id,
                    lexical_topic_id,
                    difficulty_id,
                    sentence_type
                ))

                sentence_id = cursor.fetchone()[0]

            conn.commit()
            return sentence_id

        except Exception:
            conn.rollback()
            raise



def add_sentence(
    sentence: str,
    level_id: int,
    topic_id: int,
    sentence_type: int = 0
):



    with pool.connection() as conn:
        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    INSERT INTO sentences (
                        sentence,
                        level_id,
                        grammar_topic_id,
                        type
                    )
                    VALUES (%s, %s, %s, %s)
                    RETURNING id
                """, (
                    sentence,
                    level_id,
                    topic_id,
                    sentence_type
                ))

                sentence_id = cursor.fetchone()[0]

            conn.commit()
            return sentence_id

        except Exception:
            conn.rollback()
            raise

  #отсюда и дальше заменить строку подключения на такую
#with pool.connection() as conn:

def get_sentence_from_DB(
    user_id: int,
    level_id: int,
    topic_id: int
):


    with pool.connection() as conn:
        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT s.id, s.sentence
                    FROM sentences s
                    WHERE s.level_id = %s
                    AND s.grammar_topic_id = %s
                    AND NOT EXISTS (
                        SELECT 1
                        FROM user_answers ua
                        WHERE ua.user_id = %s
                            AND ua.sentence_id = s.id
                    )
                    ORDER BY RANDOM()
                    LIMIT 1
                """, (
                    level_id,
                    topic_id,
                    user_id
                ))

                return cursor.fetchone()
        except Exception:
            conn.rollback()
            raise
    
  

def get_unused_sentences(
    user_id: int,
    level_id: int,
    grammar_topic_id: int | None,
    lexical_topic_id: int | None,
    difficulty_id: int,
    limit: int
):
    with pool.connection() as conn:
        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT
                        s.id,
                        s.sentence
                    FROM sentences s
                    WHERE s.level_id = %s
                    AND s.difficulty_id = %s

                    AND (
                        s.grammar_topic_id = %s
                        OR (
                            %s::BIGINT IS NULL
                            AND s.grammar_topic_id IS NULL
                        )
                    )

                    AND (
                        s.lexical_topic_id = %s
                        OR (
                            %s::BIGINT IS NULL
                            AND s.lexical_topic_id IS NULL
                        )
                    )

                    AND NOT EXISTS (
                        SELECT 1
                        FROM user_answers ua
                        WHERE ua.user_id = %s
                            AND ua.sentence_id = s.id
                    )

                    ORDER BY RANDOM()
                    LIMIT %s
                """, (
                    level_id,
                    difficulty_id,

                    grammar_topic_id,
                    grammar_topic_id,

                    lexical_topic_id,
                    lexical_topic_id,

                    user_id,
                    limit
                ))

                return cursor.fetchall()

        except Exception:
            conn.rollback()
            raise

def get_unused_sentence_old(
    user_id: int,
    level: int,
    topic_id: int | None = None
):

    with pool.connection() as conn:
        try:
            with conn.cursor() as cursor:

                if topic_id is None:

                    cursor.execute("""
                        SELECT s.id, s.sentence
                        FROM sentences s
                        WHERE s.level_id = %s
                        AND NOT EXISTS (
                            SELECT 1
                            FROM user_answers ua
                            WHERE ua.user_id = %s
                                AND ua.sentence_id = s.id
                        )
                        ORDER BY RANDOM()
                        LIMIT 1
                    """, (
                        level,
                        user_id
                    ))

                else:

                    cursor.execute("""
                        SELECT s.id, s.sentence
                        FROM sentences s
                        WHERE s.level_id = %s
                        AND s.grammar_topic_id = %s
                        AND NOT EXISTS (
                            SELECT 1
                            FROM user_answers ua
                            WHERE ua.user_id = %s
                                AND ua.sentence_id = s.id
                        )
                        ORDER BY RANDOM()
                        LIMIT 1
                    """, (
                        level,
                        topic_id,
                        user_id
                    ))

                return cursor.fetchone()

        except Exception:
            conn.rollback()
            raise
    

def get_blitz_sentence(
    user_id: int,
    level: int,
    topic_id: int | None = None
):

    return get_unused_sentence_old(
        user_id=user_id,
        level=level,
        topic_id=topic_id
    )


# ============================================================
# GRAMMAR TOPIC
# ============================================================

def get_grammar_topic(topic_id: int):

    with pool.connection() as conn:
        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT id, name, parent_id
                    FROM grammar_topics
                    WHERE id = %s
                """, (topic_id,))

                return cursor.fetchone()

        except Exception:
            conn.rollback()
            raise
    


def get_random_grammar_topic():

    with pool.connection() as conn:
        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT id, name
                    FROM grammar_topics
                    WHERE parent_id IS NOT NULL
                    ORDER BY RANDOM()
                    LIMIT 1
                """)

                topic = cursor.fetchone()

                if topic is None:
                    return None

                return topic[0]

        except Exception:
            conn.rollback()
            raise
    

# ============================================================
# OLD USER QUESTIONS API
# ============================================================
#
# В текущей БД таблицы user_questions нет.
# Её роль выполняет user_answers.
#
# ============================================================

def add_user_question(user_id: int, sentence_id: int):

    with pool.connection() as conn:
        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    INSERT INTO user_answers (
                        user_id,
                        sentence_id
                    )
                    VALUES (%s, %s)
                    RETURNING id
                """, (
                    user_id,
                    sentence_id
                ))

                result = cursor.fetchone()[0]

            conn.commit()
            return result

        except Exception:
            conn.rollback()
            raise



def get_used_sentence_ids(user_id: int):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT sentence_id
                    FROM user_answers
                    WHERE user_id = %s
                """, (user_id,))

                result = cursor.fetchall()

                return [row[0] for row in result]

        except Exception:
            conn.rollback()
            raise
    

# ============================================================
# USER LEVEL
# ============================================================

def get_current_user_level(user_id: int) -> int | None:

    with pool.connection() as conn:
        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT user_level
                    FROM user_levels
                    WHERE user_id = %s
                    ORDER BY created_at DESC
                    LIMIT 1
                """, (user_id,))

                result = cursor.fetchone()

                if result is None:
                    return None

                return int(result[0])

        except Exception:
            conn.rollback()
            raise
    

def get_current_user_level_id(user_id: int) -> int | None:


    with pool.connection() as conn:
        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT user_level
                    FROM user_levels
                    WHERE user_id = %s
                    ORDER BY created_at DESC
                    LIMIT 1
                """, (user_id,))

                result = cursor.fetchone()

                if result is None:
                    return None

                return int(result[0])
        except Exception:
            conn.rollback()
            raise
    
    

def save_user_level(
    user_id: int,
    level_id: int,
    estimated_level: str | None = None
):

    with pool.connection() as conn:
        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    INSERT INTO user_levels (
                        user_id,
                        user_level,
                        estimated_level,
                        source,
                        created_at
                    )
                    VALUES (%s, %s, %s, %s, %s)
                """, (
                    user_id,
                    level_id,
                    estimated_level,
                    "user",
                    datetime.now()
                ))

            conn.commit()

        except Exception:
            conn.rollback()
            raise


def get_level_name(level_id):
    t1 = time.perf_counter()
  
    print(f"Время 1: {time.perf_counter()}")
    with pool.connection() as conn:
        print(f"Время 2: {time.perf_counter()}")
        try:
            with conn.cursor() as cursor:
                print(f"Время 3: {time.perf_counter()}")

                cursor.execute("""
                    SELECT code
                    FROM levels
                    WHERE id = %s
                """, (level_id,))
                print(f"Время 4: {time.perf_counter()}")

                result = cursor.fetchone()
                print(f"Время 5: {time.perf_counter()}")

                if result is None:
                    return None

                return result[0]

        except Exception:
            conn.rollback()
            raise
      
        t2 = time.perf_counter()
        delta = t2 - t1
        print(f"Получение имения левела из БД: {round((delta) * 1000)} мс")

def get_grammar_group_name(group_id):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT name
                    FROM grammar_topics
                    WHERE id = %s
                """, (group_id,))

                result = cursor.fetchone()

                if result is None:
                    return None

                return result[0]

        except Exception:
            conn.rollback()
            raise
    

def get_grammar_topic_name(topic_id):

    if topic_id is None:
        return "Любая грамматическая тема текущего уровня"

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT name
                    FROM grammar_topics
                    WHERE id = %s
                """, (topic_id,))

                result = cursor.fetchone()

                if result is None:
                    return None

                return result[0]

        except Exception:
            conn.rollback()
            raise
    


def get_lexical_topic_name(topic_id):

    if topic_id is None:
        return "Любая тема"

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT name
                    FROM lexical_topics
                    WHERE id = %s
                """, (topic_id,))

                result = cursor.fetchone()

                if result is None:
                    return None

                return result[0]

        except Exception:
            conn.rollback()
            raise
    


def get_lexical_group_name(group_id):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT name
                    FROM lexical_topics
                    WHERE id = %s
                """, (group_id,))

                result = cursor.fetchone()

                if result is None:
                    return None

                return result[0]

        except Exception:
            conn.rollback()
            raise
    

# ============================================================
# DIFFICULTY
# ============================================================

def get_difficulty_id_by_user_id(user_id):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT difficulty_id
                    FROM user_difficulty
                    WHERE user_id = %s
                    ORDER BY created_at DESC
                    LIMIT 1
                """, (user_id,))

                result = cursor.fetchone()

                if result is not None:
                    return result[0]

                difficulty_id = 2

                cursor.execute("""
                    INSERT INTO user_difficulty (
                        user_id,
                        difficulty_id
                    )
                    VALUES (%s, %s)
                """, (
                    user_id,
                    difficulty_id
                ))

            conn.commit()

            return difficulty_id

        except Exception:
            conn.rollback()
            raise

  


def get_last_difficulty_id_by_user_id(user_id: int):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT difficulty_id
                    FROM user_difficulty
                    WHERE user_id = %s
                    ORDER BY created_at DESC
                    LIMIT 1
                """, (user_id,))

                result = cursor.fetchone()

                if result is None:

                    difficulty_id = 2

                    cursor.execute("""
                        INSERT INTO user_difficulty (
                            user_id,
                            difficulty_id
                        )
                        VALUES (%s, %s)
                    """, (
                        user_id,
                        difficulty_id
                    ))

                    conn.commit()

                    return difficulty_id

                return result[0]

        except Exception:
            conn.rollback()
            raise



def get_difficulty_name_by_id(difficulty_id: int):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT name
                    FROM difficulty
                    WHERE id = %s
                """, (difficulty_id,))

                result = cursor.fetchone()

                if result is None:
                    return None

                return result[0]

        except Exception:
            conn.rollback()
            raise
    

def save_user_difficulty(user_id: int, difficulty_id: int):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    INSERT INTO user_difficulty (
                        user_id,
                        difficulty_id,
                        created_at
                    )
                    VALUES (%s, %s, %s)
                """, (
                    user_id,
                    difficulty_id,
                    datetime.now()
                ))

            conn.commit()

        except Exception:
            conn.rollback()
            raise



def get_difficulties():

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT id, name
                    FROM difficulty
                """)

                return cursor.fetchall()

        except Exception:
            conn.rollback()
            raise
    

# ============================================================
# USER ANSWERS
# ============================================================

def save_user_answer_old(
    user_id,
    sentence_id,
    user_answer,
    ai_answer=None
):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    INSERT INTO user_answers (
                        user_id,
                        sentence_id,
                        user_answer,
                        ai_answer
                    )
                    VALUES (%s, %s, %s, %s)
                """, (
                    user_id,
                    sentence_id,
                    user_answer,
                    ai_answer
                ))

            conn.commit()

        except Exception:
            conn.rollback()
            raise


def get_last_user_sentences(user_id: int, limit: int = 10):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT s.sentence
                    FROM user_answers ua
                    JOIN sentences s
                        ON s.id = ua.sentence_id
                    WHERE ua.user_id = %s
                    ORDER BY ua.created_at DESC
                    LIMIT %s
                """, (
                    user_id,
                    limit
                ))

                result = cursor.fetchall()

                return [row[0] for row in result]

        except Exception:
            conn.rollback()
            raise
    

# ============================================================
# DELETE USER LEVELS
# ============================================================

def delete_user_levels(user_id: int):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    DELETE FROM user_levels
                    WHERE user_id = %s
                """, (user_id,))

            conn.commit()

        except Exception:
            conn.rollback()
            raise



# ============================================================
# CURRENT TRAINING FLOW
# ============================================================

async def save_user_question(user_id, sentence_id):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    INSERT INTO user_answers (
                        user_id,
                        sentence_id
                    )
                    VALUES (%s, %s)
                    RETURNING id
                """, (
                    user_id,
                    sentence_id
                ))

                result = cursor.fetchone()[0]

            conn.commit()

            return result

        except Exception:
            conn.rollback()
            raise



async def save_user_answer(user_answer_id, user_answer_text):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    UPDATE user_answers
                    SET user_answer = %s
                    WHERE id = %s
                """, (
                    user_answer_text,
                    user_answer_id
                ))

            conn.commit()

        except Exception:
            conn.rollback()
            raise



async def save_ai_answer(user_answer_id, ai_answer_text):

    with pool.connection() as conn:
            
        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    UPDATE user_answers
                    SET ai_answer = %s
                    WHERE id = %s
                """, (
                    ai_answer_text,
                    user_answer_id
                ))

            conn.commit()

        except Exception:
            conn.rollback()
            raise



# ============================================================
# SUBSCRIPTIONS
# ============================================================

def get_user_subscription(user_id):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT
                        s.id,
                        s.code,
                        s.name,
                        s.price,
                        s.period_months,
                        s.daily_limit,
                        us.started_at,
                        us.expires_at
                    FROM user_subscriptions us
                    JOIN subscriptions s
                        ON s.id = us.subscription_id
                    WHERE us.user_id = %s
                    AND us.expires_at > CURRENT_TIMESTAMP
                    ORDER BY us.expires_at DESC
                    LIMIT 1
                """, (user_id,))

                return cursor.fetchone()

        except Exception:
            conn.rollback()
            raise
       


def check_grammar_topic_access(user_id, grammar_topic_id):

    """
    В текущей схеме grammar_topics НЕТ поля subscription_required.

    Поэтому функция не может определить, является ли конкретная
    грамматическая тема Premium.

    Пока возвращаем True для существующей темы.
    Логику Premium-доступа нужно будет реализовать отдельно,
    если соответствующее поле появится в схеме.
    """

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT id
                    FROM grammar_topics
                    WHERE id = %s
                """, (grammar_topic_id,))

                topic = cursor.fetchone()

                return topic is not None

        except Exception:
              conn.rollback()
              raise
      


def get_daily_questions_count(user_id):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT COUNT(*)
                    FROM user_answers
                    WHERE user_id = %s
                    AND created_at::date = CURRENT_DATE
                """, (user_id,))

                return cursor.fetchone()[0]

        except Exception:
            conn.rollback()
            raise
    

def get_subscription(subscription_code):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT
                        id,
                        code,
                        name,
                        price,
                        period_months,
                        daily_limit
                    FROM subscriptions
                    WHERE code = %s
                """, (subscription_code,))

                return cursor.fetchone()

        except Exception:
            conn.rollback()
            raise
    


# ============================================================
# PAYMENTS
# ============================================================

def save_payment(
    user_id,
    subscription_id,
    yookassa_payment_id,
    amount,
    currency,
    status
):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    INSERT INTO payments (
                        user_id,
                        subscription_id,
                        yookassa_payment_id,
                        amount,
                        currency,
                        status
                    )
                    VALUES (%s, %s, %s, %s, %s, %s)
                    RETURNING id
                """, (
                    user_id,
                    subscription_id,
                    yookassa_payment_id,
                    amount,
                    currency,
                    status
                ))

                payment_id = cursor.fetchone()[0]

            conn.commit()

            return payment_id

        except Exception:
            conn.rollback()
            raise



def get_payment_by_yookassa_id(yookassa_payment_id):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT
                        id,
                        user_id,
                        subscription_id,
                        yookassa_payment_id,
                        amount,
                        currency,
                        status,
                        created_at,
                        paid_at
                    FROM payments
                    WHERE yookassa_payment_id = %s
                    LIMIT 1
                """, (yookassa_payment_id,))

                return cursor.fetchone()

        except Exception:
            conn.rollback()
            raise
    

def mark_payment_succeeded(yookassa_payment_id):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    UPDATE payments
                    SET
                        status = 'succeeded',
                        paid_at = CURRENT_TIMESTAMP
                    WHERE yookassa_payment_id = %s
                """, (yookassa_payment_id,))

            conn.commit()

        except Exception:
            conn.rollback()
            raise



def process_successful_payment(yookassa_payment_id):

    with pool.connection() as conn:

        try:

            with conn.cursor() as cursor:

                # ----------------------------------------------------
                # Блокируем конкретный платёж.
                #
                # Это PostgreSQL-аналог защиты от двух
                # одновременно пришедших webhook.
                # ----------------------------------------------------

                cursor.execute("""
                    SELECT
                        id,
                        user_id,
                        subscription_id,
                        status
                    FROM payments
                    WHERE yookassa_payment_id = %s
                    FOR UPDATE
                """, (yookassa_payment_id,))

                payment = cursor.fetchone()

                if payment is None:
                    raise ValueError(
                        f"Payment not found: {yookassa_payment_id}"
                    )

                payment_id = payment[0]
                user_id = payment[1]
                subscription_id = payment[2]
                status = payment[3]

                # ----------------------------------------------------
                # Уже обработан
                # ----------------------------------------------------

                if status == "succeeded":

                    conn.commit()

                    return {
                        "status": "already_processed",
                        "user_id": user_id
                    }

                # ----------------------------------------------------
                # Получаем срок подписки
                # ----------------------------------------------------

                cursor.execute("""
                    SELECT period_months
                    FROM subscriptions
                    WHERE id = %s
                """, (subscription_id,))

                subscription = cursor.fetchone()

                if subscription is None:
                    raise ValueError(
                        f"Subscription not found: {subscription_id}"
                    )

                period_months = subscription[0]

                if period_months is None:
                    raise ValueError(
                        f"Subscription has no period_months: {subscription_id}"
                    )

                started_at = datetime.now()

                expires_at = started_at + timedelta(
                    days=31 * period_months
                )

                # ----------------------------------------------------
                # Создаём подписку
                # ----------------------------------------------------

                cursor.execute("""
                    INSERT INTO user_subscriptions (
                        user_id,
                        subscription_id,
                        payment_id,
                        started_at,
                        expires_at
                    )
                    VALUES (%s, %s, %s, %s, %s)
                    ON CONFLICT (payment_id) DO NOTHING
                """, (
                    user_id,
                    subscription_id,
                    payment_id,
                    started_at,
                    expires_at
                ))

                # ----------------------------------------------------
                # Помечаем платёж как успешно обработанный
                # ----------------------------------------------------

                cursor.execute("""
                    UPDATE payments
                    SET
                        status = 'succeeded',
                        paid_at = CURRENT_TIMESTAMP
                    WHERE id = %s
                """, (payment_id,))

            conn.commit()

            return {
                "status": "activated",
                "user_id": user_id,
                "subscription_id": subscription_id,
                "payment_id": payment_id
            }

        except Exception:

            conn.rollback()
            raise



# ============================================================
# EMAIL
# ============================================================

def update_user_email(user_id, email):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    UPDATE users
                    SET email = %s
                    WHERE user_id = %s
                """, (
                    email,
                    user_id
                ))

            conn.commit()

        except Exception:
            conn.rollback()
            raise



def get_user_email(user_id):

    with pool.connection() as conn:

        try:
            with conn.cursor() as cursor:

                cursor.execute("""
                    SELECT email
                    FROM users
                    WHERE user_id = %s
                """, (user_id,))

                result = cursor.fetchone()

                if result is None:
                    return None

                return result[0]

        except Exception:
            conn.rollback()
            raise
    